import type {
  Investigation,
  TimelineNode,
  AiReasoningSection,
  ActionItem,
  ActionTableRow,
  TeamMember,
  ChatMessage,
} from '@/types';

export const investigationList: Investigation[] = [
  {
    id: 'inv-1',
    title: 'Revenue decline — North Region',
    status: 'root_cause_found',
    severity: 'critical',
    startedAgo: '14 min ago',
    owner: 'OPDOME AI',
    impact: '−18% revenue',
    signalCount: 5,
    sourceCount: 4,
    confidence: 87,
  },
  {
    id: 'inv-2',
    title: 'Warehouse B bottleneck',
    status: 'investigating',
    severity: 'critical',
    startedAgo: '27 min ago',
    owner: 'Alex Morgan',
    impact: '37 delayed orders',
    signalCount: 3,
    sourceCount: 2,
    confidence: 72,
  },
  {
    id: 'inv-3',
    title: 'Customer churn risk',
    status: 'awaiting_review',
    severity: 'medium',
    startedAgo: '1h ago',
    owner: 'OPDOME AI',
    impact: '23 high-value customers',
    signalCount: 4,
    sourceCount: 3,
    confidence: 79,
  },
  {
    id: 'inv-4',
    title: 'Inventory shortage — Product #482',
    status: 'investigating',
    severity: 'high',
    startedAgo: '2h ago',
    owner: 'OPDOME AI',
    impact: 'Stockout in 6 days',
    signalCount: 2,
    sourceCount: 1,
    confidence: 81,
  },
  {
    id: 'inv-5',
    title: 'Delivery delays — South Region',
    status: 'resolved',
    severity: 'medium',
    startedAgo: '3h ago',
    owner: 'Priya Sharma',
    impact: '−12% on-time delivery',
    signalCount: 3,
    sourceCount: 2,
    confidence: 92,
  },
  {
    id: 'inv-6',
    title: 'Supplier inconsistency detected',
    status: 'root_cause_found',
    severity: 'high',
    startedAgo: '4h ago',
    owner: 'OPDOME AI',
    impact: '8 delayed shipments',
    signalCount: 2,
    sourceCount: 3,
    confidence: 85,
  },
];

export const timelineNodes: TimelineNode[] = [
  {
    id: 'node-1',
    label: 'Revenue ↓18%',
    metric: 'Revenue',
    currentValue: '₹24.8L',
    baseline: '₹30.3L',
    change: '−18%',
    relatedEvents: ['Order volume decreased', 'Average order value stable'],
    dataSource: 'Sales System',
    confidence: 99,
  },
  {
    id: 'node-2',
    label: 'Repeat Customers ↓27%',
    metric: 'Repeat Purchase Rate',
    currentValue: '43%',
    baseline: '59%',
    change: '−27%',
    relatedEvents: ['27% drop in repeat orders', 'New customer flow unchanged'],
    dataSource: 'Customer Analytics',
    confidence: 95,
  },
  {
    id: 'node-3',
    label: 'Delivery Complaints ↑41%',
    metric: 'Complaint Rate',
    currentValue: '8.2%',
    baseline: '5.8%',
    change: '+41%',
    relatedEvents: ['41% increase in delivery complaints', 'Complaints concentrated in North region'],
    dataSource: 'Support System',
    confidence: 93,
  },
  {
    id: 'node-4',
    label: 'North Region Delays ↑63%',
    metric: 'Delivery Delay Rate',
    currentValue: '22.1%',
    baseline: '13.5%',
    change: '+63%',
    relatedEvents: ['North region delays up 63%', 'Other regions stable'],
    dataSource: 'Logistics System',
    confidence: 91,
  },
  {
    id: 'node-5',
    label: 'Warehouse B Processing Time ↑52%',
    metric: 'Avg Processing Time',
    currentValue: '4.2 hrs',
    baseline: '2.8 hrs',
    change: '+52%',
    relatedEvents: ['Processing time 52% above baseline', 'Bottleneck at packing station 3'],
    dataSource: 'Warehouse Management',
    confidence: 88,
  },
  {
    id: 'node-6',
    label: 'Staff Capacity ↓19%',
    metric: 'Staff Utilization',
    currentValue: '61%',
    baseline: '80%',
    change: '−19%',
    relatedEvents: ['2 staff members on leave', 'Weekend shift understaffed'],
    dataSource: 'HR System',
    confidence: 84,
  },
  {
    id: 'node-7',
    label: 'PRIMARY BOTTLENECK — Warehouse B',
    metric: 'Root Cause',
    currentValue: 'Warehouse B',
    baseline: '—',
    change: '+52% processing time',
    relatedEvents: ['Processing backlog at Warehouse B', 'Insufficient staff capacity'],
    dataSource: 'Cross-domain analysis',
    confidence: 87,
    isRootCause: true,
  },
];

export const aiReasoning: AiReasoningSection[] = [
  {
    title: 'Detected',
    items: ['Revenue declined 18%.'],
  },
  {
    title: 'Correlated Signals',
    items: [
      'Repeat purchases declined 27%.',
      'Delivery complaints increased 41%.',
      'North region delays increased 63%.',
    ],
  },
  {
    title: 'Root Cause',
    items: ['Warehouse B processing time increased 52%.'],
  },
  {
    title: 'Contributing Factors',
    items: ['Staff capacity below expected level.', 'Inventory processing backlog.'],
  },
];

export const suggestedQuestions = [
  'Why is this considered the primary cause?',
  'What evidence supports this?',
  'What happens if we do nothing?',
  'Which customers are affected?',
  'What should we prioritize first?',
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    role: 'ai',
    text: 'I analyzed 4,218 operational events across sales, customer, delivery, and warehouse systems. The revenue decline traces back to a processing bottleneck at Warehouse B, which is cascading into delivery delays and repeat purchase loss.',
    data: [
      { label: 'Events analyzed', value: '4,218' },
      { label: 'Data sources', value: '4' },
      { label: 'Root cause confidence', value: '87%' },
    ],
  },
];

export const aiResponses: Record<string, ChatMessage> = {
  'Why is this considered the primary cause?': {
    id: 'resp-why',
    role: 'ai',
    text: 'Warehouse B is the only node in the chain where a single operational change (processing time +52%) explains all downstream effects. When I removed Warehouse B from the causal graph, the correlation between revenue decline and other signals dropped from 0.87 to 0.31.',
    data: [
      { label: 'Correlation with cause', value: '0.87' },
      { label: 'Correlation without', value: '0.31' },
      { label: 'Confidence', value: '87%' },
    ],
  },
  'What evidence supports this?': {
    id: 'resp-evidence',
    role: 'ai',
    text: 'Five independent signals converge on Warehouse B. Processing time increased 52%, which directly caused 37 delayed orders. Those delays drove a 41% spike in complaints, which led to a 27% drop in repeat purchases, ultimately reducing revenue by 18%.',
    data: [
      { label: 'Signals converging', value: '5' },
      { label: 'Data sources', value: '4' },
      { label: 'Delayed orders', value: '37' },
    ],
  },
  'What happens if we do nothing?': {
    id: 'resp-nothing',
    role: 'ai',
    text: 'Based on current trajectory, revenue will decline an additional 8-12% over the next 14 days. Customer churn risk will escalate for 23 high-value customers. Warehouse B backlog will grow to approximately 60+ delayed orders.',
    data: [
      { label: 'Projected revenue loss', value: '−8 to −12%' },
      { label: 'At-risk customers', value: '23' },
      { label: 'Projected delayed orders', value: '60+' },
    ],
  },
  'Which customers are affected?': {
    id: 'resp-customers',
    role: 'ai',
    text: '23 high-value customers have unresolved complaints tied to delayed deliveries from Warehouse B. 15 of these are in the North region. 8 have placed 3+ orders in the last 90 days and are at high churn risk.',
    data: [
      { label: 'Affected customers', value: '23' },
      { label: 'North region', value: '15' },
      { label: 'High churn risk', value: '8' },
    ],
  },
  'What should we prioritize first?': {
    id: 'resp-priority',
    role: 'ai',
    text: 'I recommend a 4-action plan: (1) Reallocate staff to Warehouse B immediately, (2) Prioritize 37 delayed high-value orders, (3) Create customer recovery tasks for the 23 affected customers, (4) Flag inventory item #482 for procurement. Expected impact: processing time −31%, delayed orders −42%.',
    data: [
      { label: 'Actions recommended', value: '4' },
      { label: 'Processing time reduction', value: '−31%' },
      { label: 'Delayed order reduction', value: '−42%' },
    ],
  },
};

export const recommendedActions: ActionItem[] = [
  {
    id: 'act-1',
    number: 1,
    title: 'Reallocate 2 available employees to Warehouse B',
    priority: 'high',
    expectedImpact: 'Processing time −18%',
    reason: 'Staff capacity at 61% is the primary driver of the processing bottleneck. Adding 2 employees from available pool restores capacity to 85%.',
    effort: '2 hours',
    owner: 'Operations Manager',
  },
  {
    id: 'act-2',
    number: 2,
    title: 'Prioritize 37 delayed high-value orders',
    priority: 'critical',
    expectedImpact: 'Delivery delay reduction',
    reason: '37 orders are delayed due to Warehouse B backlog. Prioritizing these first prevents further customer churn and complaint escalation.',
    effort: '4 hours',
    owner: 'Warehouse Lead',
  },
  {
    id: 'act-3',
    number: 3,
    title: 'Create customer recovery tasks',
    priority: 'high',
    expectedImpact: 'Churn risk reduction',
    reason: '23 high-value customers have unresolved complaints. Proactive outreach can recover 60-70% before churn decision point.',
    effort: '1 day',
    owner: 'Customer Success',
    affectedCustomers: 23,
  },
  {
    id: 'act-4',
    number: 4,
    title: 'Flag inventory item #482 for procurement',
    priority: 'medium',
    expectedImpact: 'Stockout prevention',
    reason: 'Product #482 will fall below safety stock in 6 days. Procurement lead time is 4 days. Flagging now prevents a secondary stockout.',
    effort: '30 min',
    owner: 'Procurement',
    riskNote: 'Stockout in 6 days',
  },
];

export const actionsTableData: ActionTableRow[] = [
  {
    id: 'ar-1',
    title: 'Reallocate staff to Warehouse B',
    source: 'Revenue decline investigation',
    owner: 'Alex Morgan',
    priority: 'high',
    status: 'awaiting_approval',
    expectedImpact: 'Processing time −18%',
  },
  {
    id: 'ar-2',
    title: 'Prioritize 37 delayed orders',
    source: 'Revenue decline investigation',
    owner: 'Warehouse Lead',
    priority: 'critical',
    status: 'awaiting_approval',
    expectedImpact: 'Delay reduction',
  },
  {
    id: 'ar-3',
    title: 'Customer recovery outreach — 23 customers',
    source: 'Customer churn investigation',
    owner: 'Customer Success',
    priority: 'high',
    status: 'awaiting_approval',
    expectedImpact: 'Churn risk reduction',
  },
  {
    id: 'ar-4',
    title: 'Flag inventory #482 for procurement',
    source: 'Inventory shortage investigation',
    owner: 'Procurement',
    priority: 'medium',
    status: 'scheduled',
    expectedImpact: 'Stockout prevention',
  },
  {
    id: 'ar-5',
    title: 'Supplier follow-up — 8 delayed shipments',
    source: 'Supplier inconsistency',
    owner: 'Alex Morgan',
    priority: 'high',
    status: 'in_progress',
    expectedImpact: 'Shipment recovery',
  },
  {
    id: 'ar-6',
    title: 'Route optimization — South Region',
    source: 'Delivery delay investigation',
    owner: 'Logistics',
    priority: 'medium',
    status: 'completed',
    expectedImpact: 'On-time delivery +12%',
  },
  {
    id: 'ar-7',
    title: 'Emergency restock — Product #371',
    source: 'Inventory alert',
    owner: 'Procurement',
    priority: 'critical',
    status: 'failed',
    expectedImpact: 'Stockout occurred',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Alex',
    initials: 'AM',
    pending: 12,
    highPriority: 3,
    capacity: 78,
    status: 'balanced',
  },
  {
    id: 'tm-2',
    name: 'Priya',
    initials: 'PS',
    pending: 27,
    highPriority: 8,
    capacity: 112,
    status: 'overloaded',
  },
  {
    id: 'tm-3',
    name: 'Rahul',
    initials: 'RK',
    pending: 8,
    highPriority: 1,
    capacity: 51,
    status: 'available',
  },
];

export const productivityData = {
  before: [
    { label: 'Manual analysis', value: '6.5 hrs/week' },
    { label: 'Task coordination', value: '4.2 hrs/week' },
    { label: 'Issue investigation', value: '5.1 hrs/week' },
  ],
  withOpdome: [
    'Automated monitoring',
    'AI-assisted investigation',
    'AI-prioritized actions',
    'Human approval',
    'Outcome measurement',
  ],
  timeSaved: '9.4 hrs/week',
};

export const executionSteps = [
  { id: 'step-1', label: 'Approved', status: 'done' as const },
  { id: 'step-2', label: 'Creating tasks', status: 'done' as const },
  { id: 'step-3', label: 'Reassigning work', status: 'done' as const },
  { id: 'step-4', label: 'Updating priorities', status: 'done' as const },
  { id: 'step-5', label: 'Monitoring impact', status: 'active' as const },
];
